#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BlinkIDDemo.TestApp.Resource", IsApplication=true)]

namespace BlinkIDDemo.TestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int animateRotation = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int animationDuration = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int centered = 2130771972;
			
			// aapt resource value: 0x7f01000f
			public const int clipPadding = 2130771983;
			
			// aapt resource value: 0x7f01001b
			public const int fadeDelay = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int fadeLength = 2130771996;
			
			// aapt resource value: 0x7f01001a
			public const int fades = 2130771994;
			
			// aapt resource value: 0x7f010008
			public const int fillColor = 2130771976;
			
			// aapt resource value: 0x7f010010
			public const int footerColor = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int footerIndicatorHeight = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int footerIndicatorStyle = 2130771986;
			
			// aapt resource value: 0x7f010014
			public const int footerIndicatorUnderlinePadding = 2130771988;
			
			// aapt resource value: 0x7f010011
			public const int footerLineHeight = 2130771985;
			
			// aapt resource value: 0x7f010015
			public const int footerPadding = 2130771989;
			
			// aapt resource value: 0x7f01000e
			public const int gapWidth = 2130771982;
			
			// aapt resource value: 0x7f010000
			public const int initialOrientation = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int linePosition = 2130771990;
			
			// aapt resource value: 0x7f01000d
			public const int lineWidth = 2130771981;
			
			// aapt resource value: 0x7f010009
			public const int pageColor = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int radius = 2130771978;
			
			// aapt resource value: 0x7f010003
			public const int rotatable = 2130771971;
			
			// aapt resource value: 0x7f010017
			public const int selectedBold = 2130771991;
			
			// aapt resource value: 0x7f010005
			public const int selectedColor = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public const int snap = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int strokeColor = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int strokeWidth = 2130771974;
			
			// aapt resource value: 0x7f010018
			public const int titlePadding = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int topPadding = 2130771993;
			
			// aapt resource value: 0x7f010007
			public const int unselectedColor = 2130771975;
			
			// aapt resource value: 0x7f01001d
			public const int vpiCirclePageIndicatorStyle = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int vpiIconPageIndicatorStyle = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int vpiLinePageIndicatorStyle = 2130771999;
			
			// aapt resource value: 0x7f010021
			public const int vpiTabPageIndicatorStyle = 2130772001;
			
			// aapt resource value: 0x7f010020
			public const int vpiTitlePageIndicatorStyle = 2130772000;
			
			// aapt resource value: 0x7f010022
			public const int vpiUnderlinePageIndicatorStyle = 2130772002;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_centered = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_circle_indicator_snap = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int default_line_indicator_centered = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int default_title_indicator_selected_bold = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int default_underline_indicator_fades = 2131230724;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06001a
			public const int default_circle_indicator_fill_color = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int default_circle_indicator_page_color = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int default_circle_indicator_stroke_color = 2131099676;
			
			// aapt resource value: 0x7f060000
			public const int default_frame = 2131099648;
			
			// aapt resource value: 0x7f06001d
			public const int default_line_indicator_selected_color = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int default_line_indicator_unselected_color = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int default_title_indicator_footer_color = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int default_title_indicator_selected_color = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int default_title_indicator_text_color = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int default_underline_indicator_selected_color = 2131099682;
			
			// aapt resource value: 0x7f060001
			public const int formDetect_frame = 2131099649;
			
			// aapt resource value: 0x7f060035
			public const int green_button_background = 2131099701;
			
			// aapt resource value: 0x7f060023
			public const int green_button_pressed_background = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int green_button_unpressed_background = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int greendark = 2131099685;
			
			// aapt resource value: 0x7f060002
			public const int greenlight = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int helpButtonBackgroundDisabled = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int helpButtonBackgroundNormal = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int helpButtonBackgroundPressed = 2131099653;
			
			// aapt resource value: 0x7f060026
			public const int helpButtonBorder = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int helpButtonForeground = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int help_background = 2131099688;
			
			// aapt resource value: 0x7f060006
			public const int help_background_blink_ocr = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int max_quality_ocr_color = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int mbButtonBackgroundDisabled = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int mbButtonBackgroundNormal = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int mbButtonBackgroundPressed = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int mbButtonBorder = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int mbButtonForeground = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int med_quality_ocr_color = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int min_quality_ocr_color = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int ocr_line_background = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int ocr_line_help_background = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int overlay_background_blink_ocr = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int recognized_frame = 2131099666;
			
			// aapt resource value: 0x7f060036
			public const int red_button_background = 2131099702;
			
			// aapt resource value: 0x7f060029
			public const int red_button_pressed_background = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int red_button_unpressed_background = 2131099690;
			
			// aapt resource value: 0x7f060013
			public const int result_background_blink_ocr = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int statusBackground = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int statusForeground = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int text_gray_blink_ocr = 2131099670;
			
			// aapt resource value: 0x7f06002b
			public const int text_light = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int text_white = 2131099692;
			
			// aapt resource value: 0x7f060017
			public const int text_white_blink_ocr = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int textback = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int transparent = 2131099673;
			
			// aapt resource value: 0x7f06002d
			public const int vpi__background_holo_dark = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int vpi__background_holo_light = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int vpi__bright_foreground_disabled_holo_dark = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int vpi__bright_foreground_disabled_holo_light = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int vpi__bright_foreground_holo_dark = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int vpi__bright_foreground_holo_light = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int vpi__bright_foreground_inverse_holo_dark = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int vpi__bright_foreground_inverse_holo_light = 2131099700;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070005
			public const int activity_horizontal_margin = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int activity_horizontal_margin_blink_ocr = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int activity_vertical_margin = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int activity_vertical_margin_blink_ocr = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int default_circle_indicator_radius = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int default_circle_indicator_stroke_width = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int default_line_indicator_gap_width = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int default_line_indicator_line_width = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int default_line_indicator_stroke_width = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int default_title_indicator_clip_padding = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int default_title_indicator_footer_indicator_height = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int default_title_indicator_footer_indicator_underline_padding = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int default_title_indicator_footer_line_height = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int default_title_indicator_footer_padding = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int default_title_indicator_text_size = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int default_title_indicator_title_padding = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int default_title_indicator_top_padding = 2131165203;
			
			// aapt resource value: 0x7f070002
			public const int result_horizontal_margin_blink_ocr = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int result_vertical_margin_blink_ocr = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int text_size_blink_ocr = 2131165188;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int camera_denied = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dot = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int exit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int exit_blink_ocr = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int flashlight_blink_ocr = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int flashlight_inverse_blink_ocr = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int help_blink_ocr = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_exit = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_exit_blink_ocr = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_exit_selected = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_exit_selected_blink_ocr = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_flashlight_blink_ocr = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_flashlight_selected_blink_ocr = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_help_blink_ocr = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_help_selected_blink_ocr = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_ok_big_blink_ocr = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_ok_big_selected_blink_ocr = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int lightoff = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int lighton = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int logo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int mb_logo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int microblink_button = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ok_big_blink_ocr = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int rounded_border = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int scan_corner_ll_blink_ocr = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int scan_corner_lr_blink_ocr = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int scan_corner_ul_blink_ocr = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int scan_corner_ur_blink_ocr = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0007
			public const int bottom = 2131427335;
			
			// aapt resource value: 0x7f0b0022
			public const int btnAccept = 2131427362;
			
			// aapt resource value: 0x7f0b001a
			public const int btnExit = 2131427354;
			
			// aapt resource value: 0x7f0b001c
			public const int btnFlash = 2131427356;
			
			// aapt resource value: 0x7f0b001b
			public const int btnHelp = 2131427355;
			
			// aapt resource value: 0x7f0b000b
			public const int camera_ask_main = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int camera_ask_permission_button = 2131427340;
			
			// aapt resource value: 0x7f0b0010
			public const int defaultBackButton = 2131427344;
			
			// aapt resource value: 0x7f0b0014
			public const int defaultHelpButton = 2131427348;
			
			// aapt resource value: 0x7f0b0013
			public const int defaultStatusTextView = 2131427347;
			
			// aapt resource value: 0x7f0b0011
			public const int defaultTorchButton = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int default_photopay_viewfinder = 2131427346;
			
			// aapt resource value: 0x7f0b0016
			public const int header = 2131427350;
			
			// aapt resource value: 0x7f0b000d
			public const int imageView1 = 2131427341;
			
			// aapt resource value: 0x7f0b0017
			public const int image_logo = 2131427351;
			
			// aapt resource value: 0x7f0b0025
			public const int imgLL = 2131427365;
			
			// aapt resource value: 0x7f0b0026
			public const int imgLR = 2131427366;
			
			// aapt resource value: 0x7f0b0023
			public const int imgUL = 2131427363;
			
			// aapt resource value: 0x7f0b0024
			public const int imgUR = 2131427364;
			
			// aapt resource value: 0x7f0b001e
			public const int indicator = 2131427358;
			
			// aapt resource value: 0x7f0b0000
			public const int inversePortrait = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int landscapeLeft = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int landscapeRight = 2131427330;
			
			// aapt resource value: 0x7f0b0020
			public const int layResult = 2131427360;
			
			// aapt resource value: 0x7f0b0015
			public const int main = 2131427349;
			
			// aapt resource value: 0x7f0b0004
			public const int none = 2131427332;
			
			// aapt resource value: 0x7f0b0003
			public const int portrait = 2131427331;
			
			// aapt resource value: 0x7f0b000a
			public const int rec_view = 2131427338;
			
			// aapt resource value: 0x7f0b0019
			public const int recognizerList = 2131427353;
			
			// aapt resource value: 0x7f0b000f
			public const int scanOcr = 2131427343;
			
			// aapt resource value: 0x7f0b0009
			public const int segment_scan_root = 2131427337;
			
			// aapt resource value: 0x7f0b000e
			public const int textView1 = 2131427342;
			
			// aapt resource value: 0x7f0b0008
			public const int top = 2131427336;
			
			// aapt resource value: 0x7f0b0005
			public const int triangle = 2131427333;
			
			// aapt resource value: 0x7f0b001d
			public const int txtMessage = 2131427357;
			
			// aapt resource value: 0x7f0b0021
			public const int txtResult = 2131427361;
			
			// aapt resource value: 0x7f0b0018
			public const int txtTitle = 2131427352;
			
			// aapt resource value: 0x7f0b0006
			public const int underline = 2131427334;
			
			// aapt resource value: 0x7f0b001f
			public const int viewpager = 2131427359;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_orientation = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_title_indicator_footer_indicator_style = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int default_title_indicator_line_position = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int default_underline_indicator_fade_delay = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int default_underline_indicator_fade_length = 2131296260;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_blink_ocr = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int camera_permission_overlay = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int camera_splash = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int default_barcode_camera_overlay = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int default_mb_viewfinder = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int overlay_blink_ocr = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int page_element_blink_ocr = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int viewfinder_blink_ocr = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int device_list = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ocr_model = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int Align = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int AlignBarcode = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int AlignOcrLine = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int AutofocusFail = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int CameraAtAngle = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int CameraTooHigh = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Copied = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int Copy = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int CustomUIForbidden = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int FeatureUnsuportedAndroidVersion = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int FeatureUnsuportedAutofocus = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int FeatureUnsuportedDevice = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int FullRecognition = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int InvalidLicense = 2131034129;
			
			// aapt resource value: 0x7f050036
			public const int IsDataCorrect = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int Label = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int NoBack = 2131034168;
			
			// aapt resource value: 0x7f050012
			public const int NoRecognition = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int NoRecognizers = 2131034131;
			
			// aapt resource value: 0x7f050039
			public const int PPAddress = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int PPBarcodeData = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int PPBarcodeRawData = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int PPBarcodeType = 2131034172;
			
			// aapt resource value: 0x7f050014
			public const int PPCancel = 2131034132;
			
			// aapt resource value: 0x7f05003d
			public const int PPDateOfBirth = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int PPDateOfExpiry = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int PPDocumentCode = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int PPDocumentNumber = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int PPDriverNumber = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int PPExpiryDate = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int PPExtendedBarcodeData = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int PPFirstName = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int PPFullName = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int PPIssueDate = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int PPIssuer = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int PPLastName = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int PPMRZText = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int PPNRICNumber = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int PPNationality = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int PPOpt1 = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int PPOpt2 = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int PPPlaceOfBirth = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int PPPrimaryId = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int PPReligion = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int PPSecondaryId = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int PPSex = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int PPUncertain = 2131034195;
			
			// aapt resource value: 0x7f050015
			public const int PPUse = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int PartialDetected = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int PartialRecognition = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int Processing = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int ResultList = 2131034137;
			
			// aapt resource value: 0x7f050054
			public const int Value = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int YesPay = 2131034197;
			
			// aapt resource value: 0x7f050028
			public const int action_settings = 2131034152;
			
			// aapt resource value: 0x7f050033
			public const int amount_msg = 2131034163;
			
			// aapt resource value: 0x7f050032
			public const int amount_title = 2131034162;
			
			// aapt resource value: 0x7f050056
			public const int app_name = 2131034198;
			
			// aapt resource value: 0x7f050024
			public const int blinkid = 2131034148;
			
			// aapt resource value: 0x7f050029
			public const int hello_world = 2131034153;
			
			// aapt resource value: 0x7f05002d
			public const int help_msg_01 = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int help_msg_02 = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int help_msg_03 = 2131034159;
			
			// aapt resource value: 0x7f050035
			public const int iban_msg = 2131034165;
			
			// aapt resource value: 0x7f050034
			public const int iban_title = 2131034164;
			
			// aapt resource value: 0x7f05001a
			public const int loading = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int mbCameraNotAllowed = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int mbCameraNotReady = 2131034140;
			
			// aapt resource value: 0x7f050000
			public const int mbCameraPermissionRequired = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mbEnableCamera = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int mbEnablePermissionHelp = 2131034114;
			
			// aapt resource value: 0x7f05001d
			public const int mbErrorInitializing = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int mbHelp = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int mbHome = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int mbLightOff = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int mbLightOn = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int mbOK = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int mbOcrLineHelpMessage = 2131034147;
			
			// aapt resource value: 0x7f050003
			public const int mbWarningTitle = 2131034115;
			
			// aapt resource value: 0x7f05002c
			public const int nothingEnabledMsg = 2131034156;
			
			// aapt resource value: 0x7f05002b
			public const int nothingEnabledTitle = 2131034155;
			
			// aapt resource value: 0x7f050025
			public const int photopayOK = 2131034149;
			
			// aapt resource value: 0x7f050031
			public const int raw_msg = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int raw_title = 2131034160;
			
			// aapt resource value: 0x7f050026
			public const int scanId = 2131034150;
			
			// aapt resource value: 0x7f05002a
			public const int title_activity_main = 2131034154;
			
			// aapt resource value: 0x7f050027
			public const int title_activity_your = 2131034151;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int FancyGreenButtonBar = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int FancyRedButtonBar = 2131361793;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[]
			{
					16842948,
					16842964,
					2130771972,
					2130771974,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public const int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public const int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_fillColor = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_pageColor = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_radius = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_snap = 7;
			
			// aapt resource value: 8
			public const int CirclePageIndicator_strokeColor = 8;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_strokeWidth = 3;
			
			public static int[] LinePageIndicator = new int[]
			{
					16842964,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771981,
					2130771982};
			
			// aapt resource value: 0
			public const int LinePageIndicator_android_background = 0;
			
			// aapt resource value: 1
			public const int LinePageIndicator_centered = 1;
			
			// aapt resource value: 6
			public const int LinePageIndicator_gapWidth = 6;
			
			// aapt resource value: 5
			public const int LinePageIndicator_lineWidth = 5;
			
			// aapt resource value: 2
			public const int LinePageIndicator_selectedColor = 2;
			
			// aapt resource value: 3
			public const int LinePageIndicator_strokeWidth = 3;
			
			// aapt resource value: 4
			public const int LinePageIndicator_unselectedColor = 4;
			
			public static int[] RecognizerView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int RecognizerView_animateRotation = 1;
			
			// aapt resource value: 2
			public const int RecognizerView_animationDuration = 2;
			
			// aapt resource value: 0
			public const int RecognizerView_initialOrientation = 0;
			
			public static int[] RecognizerView_LayoutParams = new int[]
			{
					2130771971};
			
			// aapt resource value: 0
			public const int RecognizerView_LayoutParams_rotatable = 0;
			
			public static int[] TitlePageIndicator = new int[]
			{
					16842901,
					16842904,
					16842964,
					2130771973,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int TitlePageIndicator_android_background = 2;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_android_textColor = 1;
			
			// aapt resource value: 0
			public const int TitlePageIndicator_android_textSize = 0;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_clipPadding = 4;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerColor = 5;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_footerIndicatorHeight = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_footerIndicatorStyle = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerLineHeight = 6;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_footerPadding = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_linePosition = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_selectedBold = 12;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_selectedColor = 3;
			
			// aapt resource value: 13
			public const int TitlePageIndicator_titlePadding = 13;
			
			// aapt resource value: 14
			public const int TitlePageIndicator_topPadding = 14;
			
			public static int[] UnderlinePageIndicator = new int[]
			{
					16842964,
					2130771973,
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int UnderlinePageIndicator_android_background = 0;
			
			// aapt resource value: 3
			public const int UnderlinePageIndicator_fadeDelay = 3;
			
			// aapt resource value: 4
			public const int UnderlinePageIndicator_fadeLength = 4;
			
			// aapt resource value: 2
			public const int UnderlinePageIndicator_fades = 2;
			
			// aapt resource value: 1
			public const int UnderlinePageIndicator_selectedColor = 1;
			
			public static int[] ViewPagerIndicator = new int[]
			{
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
			
			// aapt resource value: 4
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
